### ISSUE TITLE
About the Google Drive feature

### ISSUE THREAD

**Issue by eliasbenb** [TheNerdful8/Lecture2Gether#102]
Thank you guys for adding the feature, but it is currently very limited.

I'm not completely sure why, but your app is unable to play a specific video. It could be because of the following reasons:
- The format of the file (mp4 works, mkv doesn't)
- The size of the file (a 9mb file worked, a 2gb file didn't)

I assume that this inability to play some files is either due to the Google API (being unable to send requests for larger files), or the player you use (being unable to play specific formats of videos, i.e mkv).

**Comment by Flova** [comment]
I think the problem has been solved in the comments under issue #83. 
If not feel free to reopen this issue again.
