### ISSUE TITLE
Show video url to all users in a room

### ISSUE THREAD

**Issue by timonegk** [TheNerdful8/Lecture2Gether#25]
For lecture2go, the original link should be displayed instead of the m3u8 link.

**Comment by Flova** [comment]
Is this still important when we show the metadata aka. tile, ... ?

**Comment by Flova** [comment]
Ping

**Comment by fredericobormann** [comment]
I think it's not important anymore. In my opinion, it's even better, if the url is not displayed in upper toolbar, since it eliminates human interaction errors, when you are trying to insert a new url.

**Comment by ftsell** [comment]
I still think it's weird.
maybe a different solution would be to display the url (in small) in the video metadata

**Comment by Flova** [comment]
Maybe a tooltip or link at some point in the meta description.

**Comment by Flova** [comment]
But I would also be fine if we drop this feature like @fredericobormann suggested.

**Comment by Flova** [comment]
Oh, I see. This is a cool solution.
I think this solves this issue. Are you okay if this issue is closed?

**Comment by fredericobormann** [comment]
As nobody seems to disagree, I close the issue ;)
