### ISSUE TITLE
Improve site using Lighthouse Report

### ISSUE THREAD

**Issue by ftsell** [TheNerdful8/Lecture2Gether#68]
I have taken the liberty to audit our page using Chromium's Lighthouse audit suite and the result is somewhat lacking:
![image](https://user-images.githubusercontent.com/12398140/85672733-7c639380-b6c3-11ea-97fb-5859a22f6b66.png)
Here is the full [report](https://github.com/TheNerdful8/Lecture2Gether/files/4829567/lighthouse_report.pdf).

We should incorporate as many recommendations as possible.

**Comment by Flova** [comment]
A subsection (SEO / Meta tags) is also mentioned in #60.
