### ISSUE TITLE
Possibility of syncing a Google Drive stream?

### ISSUE THREAD

**Issue by eliasbenb** [TheNerdful8/Lecture2Gether#83]
Would it be possible to add support for Google Drive streams if the stream link was shared publicly?
It seems possible since YouTube and Google Drive use the same platform, but I don't know much about the technicalities.

This feature would be a game changer for me.
Great repo btw <3

**Comment by Flova** [comment]
First of all, thank you for your feature request!

After a bit of research, it seems like files on google drives are accessible via an API at  `https://www.googleapis.com/drive/v3/files/<FILE_ID>?key=<GOOGLE_API_KEY>&alt=media`. The `FILE_ID` can be acquired via the file share link (e.g. `https://drive.google.com/file/d/<FILE_ID>/view?usp=sharing`) from google drive. 
A Google API key is also available in the backend, but handing it to the frontend as a streaming URL seems a bit odd. There has to be another way for this. Any Ideas?

**Comment by Flova** [comment]
Related Links:
https://github.com/videojs/video.js/issues/2027
https://stackoverflow.com/questions/47041929/does-google-drive-api-allow-us-to-download-public-file-without-authentication

**Comment by eliasbenb** [comment]
Ok so from what I understand, (for YouTube at least) you're using iFrame embeddable videos as the source correct?
If that's the case, Google Drive allows for iFrame, so this might be easy to implement.

How to get the iFrame code is shown [here](http://sangsoonam.github.io/2019/07/27/how-to-embed-a-google-drive-video.html)

**Comment by Flova** [comment]
We use [video.js](https://github.com/videojs/video.js) for better software control and a more consistent style. Video.js than chooses the correct player. This can be a normal js mp4 player or for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) reasons a youtube embedded player inside an iframe. It could be possible to adapted video.js to support google drive in the same way it supports youtube iframes, but video.js is a quite big and complicated project. A fork like that is not that easy. 
Therefore it is currently the easiest option to use the Google API with and the mp4 playback of video.js. The only problem is the exposed API key.

**Comment by Flova** [comment]
Exposing the API key seems to be unavoidable in this case. Google recommends having a different key for each service. In this case, another one for google drive which is restricted for google drive usage only. In addition, Google allows us to configure a referrer site restriction so that the key is visible, but only usable from e.g. [lecuture2gether.eu](lecuture2gether.eu).eu.

**Comment by Flova** [comment]
In addition to the feature being merged and this issue is closed it may take some time for the keys to be added to the production server. 

@eliasbenb 
We will inform you here if the feature is available on https://lecture2gether.eu.

**Comment by Flova** [comment]
@eliasbenb
The feature is now available on [https://lecture2gether.eu](https://lecture2gether.eu). But make sure your share link is publicly available without a login.

Fell free to open an issue if you have any feedback, bugs, or other feature requests.

**Comment by eliasbenb** [comment]
> @eliasbenb
> The feature is now available on https://lecture2gether.eu. But make sure your share link is publicly available without a login.
> 
> Fell free to open an issue if you have any feedback, bugs, or other feature requests.

It's not working for me.

Do I use the link you get when you choose 'Get shareable link'?

**Comment by eliasbenb** [comment]
Ok, after further testing I found that 1 file works whilst another doesn't.

The working file is:
- 9MB
- Formatted to mp4

The not working file is:
- 2GB
- Formatted to mkv

So does the Google drive API not support larger files
Or does the player not support mkv files?

**Comment by Flova** [comment]
First of all, thank you for the feedback.
The link is the right one. Sometimes you need to select that the video link can be used without login.
Sadly mkv is not supported via video.js

**Comment by eliasbenb** [comment]
> First of all, thank you for the feedback.
> The link is the right one. Sometimes you need to select that the video link can be used without login.
> Sadly mkv is not supported via video.js

Yep I'm an idiot, of course mkv files don't work, were playing a video thought a browser (-_-)
